import localFont from "next/font/local";
import "./globals.css";
import ReduxProvide from "@/app/components/ReduxProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Urabn Cart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvide>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ReduxProvide>
  );
}
