export const dummyProduct =
  "https://plus.unsplash.com/premium_photo-1675186049409-f9f8f60ebb5e?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Y2xvdGhpbmd8ZW58MHx8MHx8fDA%3D";

export const dummyProducts = [
  {
    id: 1,
    title: "Essence Mascara Lash Princess",
    description:
      "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
    category: "beauty",
    price: 9.99,
    discountPercentage: 7.17,
    rating: 4.94,
    stock: 5,
    tags: ["beauty", "mascara"],
    brand: "Essence",
    sku: "RCH45Q1A",
    weight: 2,
    dimensions: { width: 23.17, height: 14.43, depth: 28.01 },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "John Doe",
        reviewerEmail: "john.doe@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Not as described!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Scarlett Wright",
        reviewerEmail: "scarlett.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 24,
    meta: {
      createdAt: "2024-05-23T08:56:21.618Z",
      updatedAt: "2024-05-23T08:56:21.618Z",
      barcode: "9164035109868",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png",
  },
  {
    id: 2,
    title: "Eyeshadow Palette with Mirror",
    description:
      "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
    category: "beauty",
    price: 19.99,
    discountPercentage: 5.5,
    rating: 3.28,
    stock: 44,
    tags: ["beauty", "eyeshadow"],
    brand: "Glamour Beauty",
    sku: "MVCFH27F",
    weight: 3,
    dimensions: { width: 12.42, height: 8.63, depth: 29.13 },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Liam Garcia",
        reviewerEmail: "liam.garcia@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 32,
    meta: {
      createdAt: "2024-05-23T08:56:21.618Z",
      updatedAt: "2024-05-23T08:56:21.618Z",
      barcode: "2817839095220",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png",
  },
  {
    id: 3,
    title: "Powder Canister",
    description:
      "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
    category: "beauty",
    price: 14.99,
    discountPercentage: 18.14,
    rating: 3.82,
    stock: 59,
    tags: ["beauty", "face powder"],
    brand: "Velvet Touch",
    sku: "9EN8WLT2",
    weight: 8,
    dimensions: { width: 24.16, height: 10.7, depth: 11.07 },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Ethan Thompson",
        reviewerEmail: "ethan.thompson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Levi Hicks",
        reviewerEmail: "levi.hicks@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.618Z",
        reviewerName: "Hazel Gardner",
        reviewerEmail: "hazel.gardner@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 25,
    meta: {
      createdAt: "2024-05-23T08:56:21.618Z",
      updatedAt: "2024-05-23T08:56:21.618Z",
      barcode: "0516267971277",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png",
  },
  {
    id: 4,
    title: "Red Lipstick",
    description:
      "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
    category: "beauty",
    price: 12.99,
    discountPercentage: 19.03,
    rating: 2.51,
    stock: 68,
    tags: ["beauty", "lipstick"],
    brand: "Chic Cosmetics",
    sku: "O5IF1NTA",
    weight: 5,
    dimensions: { width: 14.37, height: 13.94, depth: 14.6 },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Oscar Powers",
        reviewerEmail: "oscar.powers@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Carter Rivera",
        reviewerEmail: "carter.rivera@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 6,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "9444582199406",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/thumbnail.png",
  },
  {
    id: 5,
    title: "Red Nail Polish",
    description:
      "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
    category: "beauty",
    price: 8.99,
    discountPercentage: 2.46,
    rating: 3.91,
    stock: 71,
    tags: ["beauty", "nail polish"],
    brand: "Nail Couture",
    sku: "YUIIIP4W",
    weight: 9,
    dimensions: { width: 8.11, height: 10.89, depth: 29.06 },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Evan Reed",
        reviewerEmail: "evan.reed@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Evelyn Sanchez",
        reviewerEmail: "evelyn.sanchez@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 46,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "3212847902461",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/thumbnail.png",
  },
  {
    id: 6,
    title: "Calvin Klein CK One",
    description:
      "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
    category: "fragrances",
    price: 49.99,
    discountPercentage: 0.32,
    rating: 4.85,
    stock: 17,
    tags: ["fragrances", "perfumes"],
    brand: "Calvin Klein",
    sku: "DZM2JQZE",
    weight: 5,
    dimensions: { width: 11.53, height: 14.44, depth: 6.81 },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Sophia Brown",
        reviewerEmail: "sophia.brown@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 20,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "2210136215089",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/thumbnail.png",
  },
  {
    id: 7,
    title: "Chanel Coco Noir Eau De",
    description:
      "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
    category: "fragrances",
    price: 129.99,
    discountPercentage: 18.64,
    rating: 2.76,
    stock: 41,
    tags: ["fragrances", "perfumes"],
    brand: "Chanel",
    sku: "K71HBCGS",
    weight: 4,
    dimensions: { width: 21.27, height: 28, depth: 11.89 },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Disappointing product!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Lincoln Kelly",
        reviewerEmail: "lincoln.kelly@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Lincoln Kelly",
        reviewerEmail: "lincoln.kelly@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Lucas Allen",
        reviewerEmail: "lucas.allen@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "1435582999795",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/thumbnail.png",
  },
  {
    id: 8,
    title: "Dior J'adore",
    description:
      "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
    category: "fragrances",
    price: 89.99,
    discountPercentage: 17.44,
    rating: 3.31,
    stock: 91,
    tags: ["fragrances", "perfumes"],
    brand: "Dior",
    sku: "E70NB03B",
    weight: 10,
    dimensions: { width: 21.51, height: 7, depth: 26.51 },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Zoe Nicholson",
        reviewerEmail: "zoe.nicholson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Addison Wright",
        reviewerEmail: "addison.wright@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 8,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "0887083199279",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/thumbnail.png",
  },
  {
    id: 9,
    title: "Dolce Shine Eau de",
    description:
      "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
    category: "fragrances",
    price: 69.99,
    discountPercentage: 11.47,
    rating: 2.68,
    stock: 3,
    tags: ["fragrances", "perfumes"],
    brand: "Dolce & Gabbana",
    sku: "1NBFK980",
    weight: 5,
    dimensions: { width: 17, height: 24.57, depth: 13.3 },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Xavier Wright",
        reviewerEmail: "xavier.wright@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Mila Hernandez",
        reviewerEmail: "mila.hernandez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.619Z",
        reviewerName: "Sophia Brown",
        reviewerEmail: "sophia.brown@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 9,
    meta: {
      createdAt: "2024-05-23T08:56:21.619Z",
      updatedAt: "2024-05-23T08:56:21.619Z",
      barcode: "1939383392674",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/thumbnail.png",
  },
  {
    id: 10,
    title: "Gucci Bloom Eau de",
    description:
      "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
    category: "fragrances",
    price: 79.99,
    discountPercentage: 8.9,
    rating: 2.69,
    stock: 93,
    tags: ["fragrances", "perfumes"],
    brand: "Gucci",
    sku: "FFKZ6HOF",
    weight: 10,
    dimensions: { width: 22.28, height: 17.81, depth: 27.18 },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Aria Parker",
        reviewerEmail: "aria.parker@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Natalie Harris",
        reviewerEmail: "natalie.harris@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ava Harris",
        reviewerEmail: "ava.harris@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "8232190382069",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/1.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/2.png",
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/thumbnail.png",
  },
  {
    id: 11,
    title: "Annibale Colombo Bed",
    description:
      "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
    category: "furniture",
    price: 1899.99,
    discountPercentage: 0.29,
    rating: 4.14,
    stock: 47,
    tags: ["furniture", "beds"],
    brand: "Annibale Colombo",
    sku: "4KMDTZWF",
    weight: 3,
    dimensions: { width: 28.75, height: 26.88, depth: 24.47 },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Julian Newton",
        reviewerEmail: "julian.newton@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7113807059215",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/thumbnail.png",
  },
  {
    id: 12,
    title: "Annibale Colombo Sofa",
    description:
      "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
    category: "furniture",
    price: 2499.99,
    discountPercentage: 18.54,
    rating: 3.08,
    stock: 16,
    tags: ["furniture", "sofas"],
    brand: "Annibale Colombo",
    sku: "LUU95CQP",
    weight: 3,
    dimensions: { width: 20.97, height: 19.11, depth: 25.81 },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Tyler Davis",
        reviewerEmail: "tyler.davis@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Hannah Robinson",
        reviewerEmail: "hannah.robinson@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Waste of money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "0426785817074",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/thumbnail.png",
  },
  {
    id: 13,
    title: "Bedside Table African Cherry",
    description:
      "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
    category: "furniture",
    price: 299.99,
    discountPercentage: 9.58,
    rating: 4.48,
    stock: 16,
    tags: ["furniture", "bedside tables"],
    brand: "Furniture Co.",
    sku: "OWPLTZYX",
    weight: 10,
    dimensions: { width: 25.43, height: 20.2, depth: 24.95 },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "John Doe",
        reviewerEmail: "john.doe@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Avery Carter",
        reviewerEmail: "avery.carter@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Evelyn Sanchez",
        reviewerEmail: "evelyn.sanchez@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "2913244159666",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/thumbnail.png",
  },
  {
    id: 14,
    title: "Knoll Saarinen Executive Conference Chair",
    description:
      "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
    category: "furniture",
    price: 499.99,
    discountPercentage: 15.23,
    rating: 4.11,
    stock: 47,
    tags: ["furniture", "office chairs"],
    brand: "Knoll",
    sku: "RKHVJ4FE",
    weight: 3,
    dimensions: { width: 16.59, height: 21.46, depth: 29.07 },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Leah Gutierrez",
        reviewerEmail: "leah.gutierrez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Waste of money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Stella Morris",
        reviewerEmail: "stella.morris@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "0726316339746",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/thumbnail.png",
  },
  {
    id: 15,
    title: "Wooden Bathroom Sink With Mirror",
    description:
      "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
    category: "furniture",
    price: 799.99,
    discountPercentage: 11.22,
    rating: 3.26,
    stock: 95,
    tags: ["furniture", "bathroom"],
    brand: "Bath Trends",
    sku: "7OLTIEVO",
    weight: 6,
    dimensions: { width: 7.32, height: 22.64, depth: 12.37 },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Charlotte Lopez",
        reviewerEmail: "charlotte.lopez@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "William Gonzalez",
        reviewerEmail: "william.gonzalez@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Not worth the price!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ava Harrison",
        reviewerEmail: "ava.harrison@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7839797529453",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/1.png",
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/2.png",
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/thumbnail.png",
  },
  {
    id: 16,
    title: "Apple",
    description:
      "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
    category: "groceries",
    price: 1.99,
    discountPercentage: 1.97,
    rating: 2.96,
    stock: 9,
    tags: ["fruits"],
    sku: "QTROUV79",
    weight: 8,
    dimensions: { width: 8.29, height: 5.58, depth: 12.41 },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Logan Lee",
        reviewerEmail: "logan.lee@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Elena Long",
        reviewerEmail: "elena.long@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Not as described!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Grayson Coleman",
        reviewerEmail: "grayson.coleman@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 44,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "2517819903837",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/products/images/groceries/Apple/1.png"],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Apple/thumbnail.png",
  },
  {
    id: 17,
    title: "Beef Steak",
    description:
      "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
    category: "groceries",
    price: 12.99,
    discountPercentage: 17.99,
    rating: 2.83,
    stock: 96,
    tags: ["meat"],
    sku: "BWWA2MSO",
    weight: 9,
    dimensions: { width: 23.35, height: 13.48, depth: 26.4 },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ethan Martinez",
        reviewerEmail: "ethan.martinez@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Disappointing product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Owen Fisher",
        reviewerEmail: "owen.fisher@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Scarlett Wright",
        reviewerEmail: "scarlett.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 21,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "8335515097879",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Beef%20Steak/thumbnail.png",
  },
  {
    id: 18,
    title: "Cat Food",
    description:
      "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
    category: "groceries",
    price: 8.99,
    discountPercentage: 9.57,
    rating: 2.88,
    stock: 13,
    tags: ["pet supplies", "cat food"],
    sku: "C3F8QN6O",
    weight: 9,
    dimensions: { width: 15.4, height: 13.97, depth: 25.13 },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Mateo Bennett",
        reviewerEmail: "mateo.bennett@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Aurora Barnes",
        reviewerEmail: "aurora.barnes@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ellie Stewart",
        reviewerEmail: "ellie.stewart@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 48,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "5503491330693",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/thumbnail.png",
  },
  {
    id: 19,
    title: "Chicken Meat",
    description:
      "Fresh and tender chicken meat, suitable for various culinary preparations.",
    category: "groceries",
    price: 9.99,
    discountPercentage: 10.46,
    rating: 4.61,
    stock: 69,
    tags: ["meat"],
    sku: "G5YEHW7B",
    weight: 7,
    dimensions: { width: 15.96, height: 29.24, depth: 26.25 },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Sophia Jones",
        reviewerEmail: "sophia.jones@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Harper Turner",
        reviewerEmail: "harper.turner@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 46,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "0966223559510",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/1.png",
      "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/2.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Chicken%20Meat/thumbnail.png",
  },
  {
    id: 20,
    title: "Cooking Oil",
    description:
      "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
    category: "groceries",
    price: 4.99,
    discountPercentage: 18.89,
    rating: 4.01,
    stock: 22,
    tags: ["cooking essentials"],
    sku: "Q6ZP1UY8",
    weight: 8,
    dimensions: { width: 8.18, height: 27.45, depth: 27.88 },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Mason Parker",
        reviewerEmail: "mason.parker@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Jonathan Pierce",
        reviewerEmail: "jonathan.pierce@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Alexander Hernandez",
        reviewerEmail: "alexander.hernandez@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "6707669443381",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Cooking%20Oil/thumbnail.png",
  },
  {
    id: 21,
    title: "Cucumber",
    description:
      "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
    category: "groceries",
    price: 1.49,
    discountPercentage: 11.44,
    rating: 4.71,
    stock: 22,
    tags: ["vegetables"],
    sku: "6KGF2K6Z",
    weight: 9,
    dimensions: { width: 11.04, height: 20.5, depth: 8.18 },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Elijah Hill",
        reviewerEmail: "elijah.hill@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Liam Garcia",
        reviewerEmail: "liam.garcia@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ella Cook",
        reviewerEmail: "ella.cook@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 7,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "2597004869708",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Cucumber/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Cucumber/thumbnail.png",
  },
  {
    id: 22,
    title: "Dog Food",
    description:
      "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
    category: "groceries",
    price: 10.99,
    discountPercentage: 18.15,
    rating: 2.74,
    stock: 40,
    tags: ["pet supplies", "dog food"],
    sku: "A6QRCH37",
    weight: 2,
    dimensions: { width: 29.39, height: 29.77, depth: 20.54 },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Alexander Jones",
        reviewerEmail: "alexander.jones@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Addison Wright",
        reviewerEmail: "addison.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 29,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7957222289508",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Dog%20Food/thumbnail.png",
  },
  {
    id: 23,
    title: "Eggs",
    description:
      "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
    category: "groceries",
    price: 2.99,
    discountPercentage: 5.8,
    rating: 4.46,
    stock: 10,
    tags: ["dairy"],
    sku: "YA617RI7",
    weight: 4,
    dimensions: { width: 12.3, height: 10.99, depth: 15.53 },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Mateo Perez",
        reviewerEmail: "mateo.perez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Cameron Perez",
        reviewerEmail: "cameron.perez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Aurora Barnes",
        reviewerEmail: "aurora.barnes@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 43,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7095702028776",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/products/images/groceries/Eggs/1.png"],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Eggs/thumbnail.png",
  },
  {
    id: 24,
    title: "Fish Steak",
    description:
      "Quality fish steak, suitable for grilling, baking, or pan-searing.",
    category: "groceries",
    price: 14.99,
    discountPercentage: 7,
    rating: 4.83,
    stock: 99,
    tags: ["seafood"],
    sku: "XNIH1MTA",
    weight: 8,
    dimensions: { width: 20.14, height: 8.4, depth: 10.01 },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Michael Johnson",
        reviewerEmail: "michael.johnson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Julian Newton",
        reviewerEmail: "julian.newton@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Lila Hudson",
        reviewerEmail: "lila.hudson@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 49,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "4250692197342",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/thumbnail.png",
  },
  {
    id: 25,
    title: "Green Bell Pepper",
    description:
      "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
    category: "groceries",
    price: 1.29,
    discountPercentage: 15.5,
    rating: 4.28,
    stock: 89,
    tags: ["vegetables"],
    sku: "HU7S7VQ0",
    weight: 7,
    dimensions: { width: 7.32, height: 14.31, depth: 21.38 },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ethan Thompson",
        reviewerEmail: "ethan.thompson@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "7583442707568",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Bell%20Pepper/thumbnail.png",
  },
  {
    id: 26,
    title: "Green Chili Pepper",
    description:
      "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
    category: "groceries",
    price: 0.99,
    discountPercentage: 18.51,
    rating: 4.43,
    stock: 8,
    tags: ["vegetables"],
    sku: "Y4RM3JCB",
    weight: 2,
    dimensions: { width: 18.67, height: 21.17, depth: 25.26 },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Disappointing product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Mateo Bennett",
        reviewerEmail: "mateo.bennett@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Natalie Price",
        reviewerEmail: "natalie.price@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Avery Barnes",
        reviewerEmail: "avery.barnes@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 43,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "8400326844874",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Green%20Chili%20Pepper/thumbnail.png",
  },
  {
    id: 27,
    title: "Honey Jar",
    description:
      "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
    category: "groceries",
    price: 6.99,
    discountPercentage: 1.91,
    rating: 3.5,
    stock: 25,
    tags: ["condiments"],
    sku: "BTBNIIOU",
    weight: 9,
    dimensions: { width: 26.53, height: 27.11, depth: 6.63 },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Gabriel Hayes",
        reviewerEmail: "gabriel.hayes@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "James Garcia",
        reviewerEmail: "james.garcia@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "0668665656044",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Honey%20Jar/thumbnail.png",
  },
  {
    id: 28,
    title: "Ice Cream",
    description:
      "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
    category: "groceries",
    price: 5.49,
    discountPercentage: 7.58,
    rating: 3.77,
    stock: 76,
    tags: ["desserts"],
    sku: "VEZMU1EQ",
    weight: 5,
    dimensions: { width: 17.66, height: 24.49, depth: 25.98 },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Madeline Simpson",
        reviewerEmail: "madeline.simpson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Caleb Nelson",
        reviewerEmail: "caleb.nelson@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 19,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "9603960319256",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/1.png",
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/2.png",
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/3.png",
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/4.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Ice%20Cream/thumbnail.png",
  },
  {
    id: 29,
    title: "Juice",
    description:
      "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
    category: "groceries",
    price: 3.99,
    discountPercentage: 5.45,
    rating: 3.41,
    stock: 99,
    tags: ["beverages"],
    sku: "M2K19S06",
    weight: 2,
    dimensions: { width: 8.97, height: 12.26, depth: 15.05 },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Not worth the price!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Ethan Martinez",
        reviewerEmail: "ethan.martinez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Max Parker",
        reviewerEmail: "max.parker@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 26,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "8546824122355",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/products/images/groceries/Juice/1.png"],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Juice/thumbnail.png",
  },
  {
    id: 30,
    title: "Kiwi",
    description:
      "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
    category: "groceries",
    price: 2.49,
    discountPercentage: 10.32,
    rating: 4.37,
    stock: 1,
    tags: ["fruits"],
    sku: "0X3NORB9",
    weight: 8,
    dimensions: { width: 27.3, height: 7.48, depth: 15.08 },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Dylan Wells",
        reviewerEmail: "dylan.wells@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.620Z",
        reviewerName: "Noah Hernandez",
        reviewerEmail: "noah.hernandez@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 8,
    meta: {
      createdAt: "2024-05-23T08:56:21.620Z",
      updatedAt: "2024-05-23T08:56:21.620Z",
      barcode: "3325493172934",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/products/images/groceries/Kiwi/1.png"],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Kiwi/thumbnail.png",
  },
];

export const clothCategories = [
  {
    name: "Clothing",
    subcategories: [
      {
        name: "Men",
        types: [
          "T-Shirts",
          "Polo Shirts",
          "Casual Shirts",
          "Formal Shirts",
          "Jeans",
          "Chinos",
          "Trousers",
          "Shorts",
          "Jackets",
          "Coats",
          "Sweaters",
          "Hoodies",
          "Activewear",
          "Suits",
          "Sleepwear",
          "Underwear",
          "Swimwear",
          "Vests",
        ],
      },
      {
        name: "Women",
        types: [
          "T-Shirts",
          "Tank Tops",
          "Blouses",
          "Casual Shirts",
          "Dresses",
          "Maxi Dresses",
          "Skirts",
          "Jeans",
          "Leggings",
          "Trousers",
          "Shorts",
          "Activewear",
          "Cardigans",
          "Jackets",
          "Coats",
          "Sweaters",
          "Jumpsuits",
          "Romper",
          "Sleepwear",
          "Loungewear",
          "Underwear",
          "Swimwear",
        ],
      },
      {
        name: "Kids",
        subcategories: [
          {
            name: "Boys",
            types: [
              "T-Shirts",
              "Polo Shirts",
              "Casual Shirts",
              "Shorts",
              "Jeans",
              "Trousers",
              "Sweaters",
              "Hoodies",
              "Jackets",
              "Activewear",
              "Sleepwear",
              "Swimwear",
              "Underwear",
            ],
          },
          {
            name: "Girls",
            types: [
              "T-Shirts",
              "Tank Tops",
              "Blouses",
              "Dresses",
              "Skirts",
              "Leggings",
              "Jeans",
              "Trousers",
              "Shorts",
              "Activewear",
              "Jackets",
              "Cardigans",
              "Sweaters",
              "Sleepwear",
              "Swimwear",
              "Underwear",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Footwear",
    subcategories: [
      {
        name: "Men",
        types: [
          "Casual Shoes",
          "Formal Shoes",
          "Loafers",
          "Oxfords",
          "Sneakers",
          "Sports Shoes",
          "Sandals",
          "Boots",
          "Chukka Boots",
          "Dress Boots",
          "Slippers",
        ],
      },
      {
        name: "Women",
        types: [
          "Heels",
          "Flats",
          "Ballet Flats",
          "Sneakers",
          "Sandals",
          "Boots",
          "Ankle Boots",
          "Wedges",
          "Loafers",
          "Slippers",
          "Flip Flops",
        ],
      },
      {
        name: "Kids",
        subcategories: [
          {
            name: "Boys",
            types: [
              "Sneakers",
              "Casual Shoes",
              "Sandals",
              "Boots",
              "Loafers",
              "Slippers",
            ],
          },
          {
            name: "Girls",
            types: [
              "Sneakers",
              "Flats",
              "Ballet Flats",
              "Sandals",
              "Boots",
              "Heels",
              "Slippers",
            ],
          },
        ],
      },
    ],
  },
];

// Sizes for Clothing
export const sizes = ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL"];

// Sizes for Footwear (Men)
export const menFootwearSizes = [6, 7, 8, 9, 10, 11, 12];

// Sizes for Footwear (Women)
export const womenFootwearSizes = [4, 5, 6, 7, 8, 9, 10];

// Sizes for Footwear (Kids)
export const kidsFootwearSizes = [2, 3, 4, 5, 6, 7, 8];

export const menClothing = [
  { label: "T-Shirts", key: "T-Shirts" },
  { label: "Polo Shirts", key: "Polo Shirts" },
  { label: "Casual Shirts", key: "Casual Shirts" },
  { label: "Formal Shirts", key: "Formal Shirts" },
  { label: "Jeans", key: "Jeans" },
  { label: "Chinos", key: "Chinos" },
  { label: "Trousers", key: "Trousers" },
  { label: "Shorts", key: "Shorts" },
  { label: "Jackets", key: "Jackets" },
  { label: "Coats", key: "Coats" },
  { label: "Sweaters", key: "Sweaters" },
  { label: "Hoodies", key: "Hoodies" },
  { label: "Activewear", key: "Activewear" },
  { label: "Suits", key: "Suits" },
  { label: "Sleepwear", key: "Sleepwear" },
  { label: "Underwear", key: "Underwear" },
  { label: "Swimwear", key: "Swimwear" },
  { label: "Vests", key: "Vests" },
];
export const womenClothing = [
  { label: "T-Shirts", key: "T-Shirts" },
  { label: "Tank Tops", key: "Tank Tops" },
  { label: "Blouses", key: "Blouses" },
  { label: "Casual Shirts", key: "Casual Shirts" },
  { label: "Dresses", key: "Dresses" },
  { label: "Maxi Dresses", key: "Maxi Dresses" },
  { label: "Skirts", key: "Skirts" },
  { label: "Jeans", key: "Jeans" },
  { label: "Leggings", key: "Leggings" },
  { label: "Trousers", key: "Trousers" },
  { label: "Shorts", key: "Shorts" },
  { label: "Activewear", key: "Activewear" },
  { label: "Cardigans", key: "Cardigans" },
  { label: "Jackets", key: "Jackets" },
  { label: "Coats", key: "Coats" },
  { label: "Sweaters", key: "Sweaters" },
  { label: "Jumpsuits", key: "Jumpsuits" },
  { label: "Romper", key: "Romper" },
  { label: "Sleepwear", key: "Sleepwear" },
  { label: "Loungewear", key: "Loungewear" },
  { label: "Underwear", key: "Underwear" },
  { label: "Swimwear", key: "Swimwear" },
];

export const kidsClothing = [
  { label: "T-Shirts", key: "T-Shirts" },
  { label: "Tank Tops", key: "Tank Tops" },
  { label: "Blouses", key: "Blouses" },
  { label: "Dresses", key: "Dresses" },
  { label: "Skirts", key: "Skirts" },
  { label: "Leggings", key: "Leggings" },
  { label: "Jeans", key: "Jeans" },
  { label: "Trousers", key: "Trousers" },
  { label: "Shorts", key: "Shorts" },
  { label: "Activewear", key: "Activewear" },
  { label: "Jackets", key: "Jackets" },
  { label: "Cardigans", key: "Cardigans" },
  { label: "Sweaters", key: "Sweaters" },
  { label: "Sleepwear", key: "Sleepwear" },
  { label: "Swimwear", key: "Swimwear" },
  { label: "T-Shirts", key: "T-Shirts" },
  { label: "Polo Shirts", key: "Polo Shirts" },
  { label: "Casual Shirts", key: "Casual Shirts" },
  { label: "Shorts", key: "Shorts" },
  { label: "Jeans", key: "Jeans" },
  { label: "Trousers", key: "Trousers" },
  { label: "Sweaters", key: "Sweaters" },
  { label: "Hoodies", key: "Hoodies" },
  { label: "Jackets", key: "Jackets" },
  { label: "Activewear", key: "Activewear" },
  { label: "Sleepwear", key: "Sleepwear" },
  { label: "Swimwear", key: "Swimwear" },
  { label: "Underwear", key: "Underwear" },
  { label: "Underwear", key: "Underwear" },
];

export const menFootwear = [
  { label: "Casual Shoes", key: "Casual Shoes" },
  { label: "Formal Shoes", key: "Formal Shoes" },
  { label: "Loafers", key: "Loafers" },
  { label: "Oxfords", key: "Oxfords" },
  { label: "Sneakers", key: "Sneakers" },
  { label: "Sports Shoes", key: "Sports Shoes" },
  { label: "Sandals", key: "Sandals" },
  { label: "Boots", key: "Boots" },
  { label: "Chukka Boots", key: "Chukka Boots" },
  { label: "Dress Boots", key: "Dress Boots" },
  { label: "Slippers", key: "Slippers" },
];

export const womenFootwear = [
  { label: "Heels", key: "Heels" },
  { label: "Flats", key: "Flats" },
  { label: "Ballet Flats", key: "Ballet Flats" },
  { label: "Sneakers", key: "Sneakers" },
  { label: "Sandals", key: "Sandals" },
  { label: "Boots", key: "Boots" },
  { label: "Ankle Boots", key: "Ankle Boots" },
  { label: "Wedges", key: "Wedges" },
  { label: "Loafers", key: "Loafers" },
  { label: "Slippers", key: "Slippers" },
  { label: "Flip Flops", key: "Flip Flops" },
];

export const kidsFootwear = [
  { label: "Sneakers", key: "Sneakers" },
  { label: "Casual Shoes", key: "Casual Shoes" },
  { label: "Sandals", key: "Sandals" },
  { label: "Boots", key: "Boots" },
  { label: "Loafers", key: "Loafers" },
  { label: "Slippers", key: "Slippers" },
  { label: "Sneakers", key: "Sneakers" },
  { label: "Flats", key: "Flats" },
  { label: "Ballet Flats", key: "Ballet Flats" },
  { label: "Sandals", key: "Sandals" },
  { label: "Boots", key: "Boots" },
  { label: "Heels", key: "Heels" },
  { label: "Slippers", key: "Slippers" },
];

// Colors for Clothing and Footwear
export const colors = [
  "Red",
  "Blue",
  "Green",
  "Black",
  "White",
  "Yellow",
  "Pink",
  "Purple",
  "Brown",
  "Orange",
  "Grey",
  "Navy",
];

// Materials for Clothing
// Materials for Clothing
export const clothingMaterials = [
  { label: "Cotton", key: "Cotton" },
  { label: "Wool", key: "Wool" },
  { label: "Polyester", key: "Polyester" },
  { label: "Linen", key: "Linen" },
  { label: "Silk", key: "Silk" },
  { label: "Denim", key: "Denim" },
  { label: "Rayon", key: "Rayon" },
  { label: "Nylon", key: "Nylon" },
  { label: "Leather", key: "Leather" },
  { label: "Synthetic", key: "Synthetic" },
];

// Materials for Footwear
export const footwearMaterials = [
  { label: "Leather", key: "Leather" },
  { label: "Synthetic Leather", key: "Synthetic Leather" },
  { label: "Suede", key: "Suede" },
  { label: "Canvas", key: "Canvas" },
  { label: "Rubber", key: "Rubber" },
  { label: "Textile", key: "Textile" },
  { label: "Mesh", key: "Mesh" },
];

// Fit Types for Clothing
export const fitTypes = [
  { label: "Slim Fit", key: "Slim Fit" },
  { label: "Regular Fit", key: "Regular Fit" },
  { label: "Loose Fit", key: "Loose Fit" },
  { label: "Relaxed Fit", key: "Relaxed Fit" },
  { label: "Skinny Fit", key: "Skinny Fit" },
  { label: "Straight Fit", key: "Straight Fit" },
];

// Patterns for Clothing
export const patterns = [
  { label: "Solid", key: "Solid" },
  { label: "Printed", key: "Printed" },
  { label: "Striped", key: "Striped" },
  { label: "Checked", key: "Checked" },
  { label: "Floral", key: "Floral" },
  { label: "Embroidered", key: "Embroidered" },
  { label: "Polka Dots", key: "Polka Dots" },
];

// Sleeve Types for Tops
export const sleeveTypes = [
  { label: "Sleeveless", key: "Sleeveless" },
  { label: "Half Sleeve", key: "Half Sleeve" },
  { label: "Full Sleeve", key: "Full Sleeve" },
  { label: "Three-Quarter Sleeve", key: "Three-Quarter Sleeve" },
  { label: "Cap Sleeve", key: "Cap Sleeve" },
];

// Neck Styles for Tops and Dresses
export const neckStyles = [
  { label: "Round Neck", key: "Round Neck" },
  { label: "V-Neck", key: "V-Neck" },
  { label: "Collared", key: "Collared" },
  { label: "Boat Neck", key: "Boat Neck" },
  { label: "Halter Neck", key: "Halter Neck" },
  { label: "Off-Shoulder", key: "Off-Shoulder" },
];

// Sole Materials for Footwear
export const soleMaterials = [
  { label: "Rubber", key: "Rubber" },
  { label: "PU", key: "PU" },
  { label: "Leather", key: "Leather" },
  { label: "EVA", key: "EVA" },
  { label: "PVC", key: "PVC" },
  { label: "TPR", key: "TPR" },
];

// Heel Heights for Footwear
export const heelHeights = [
  { label: "Flat", key: "Flat" },
  { label: "Low (1-2 inches)", key: "Low (1-2 inches)" },
  { label: "Medium (2-3 inches)", key: "Medium (2-3 inches)" },
  { label: "High (3-4 inches)", key: "High (3-4 inches)" },
  { label: "Very High (4+ inches)", key: "Very High (4+ inches)" },
];

export const bgColors = [
  { name: "Red-Orange", color: "#FF5733" },
  { name: "Lime Green", color: "#33FF57" },
  { name: "Blue", color: "#3357FF" },
  { name: "Khaki", color: "#F0E68C" },
  { name: "Gold", color: "#FFD700" },
  { name: "Hot Pink", color: "#FF69B4" },
  { name: "Blue Violet", color: "#8A2BE2" },
  { name: "Chartreuse", color: "#7FFF00" },
  { name: "Orange Red", color: "#FF4500" },
  { name: "Sea Green", color: "#2E8B57" },
  { name: "Steel Blue", color: "#4682B4" },
  { name: "Firebrick", color: "#B22222" },
  { name: "Cadet Blue", color: "#5F9EA0" },
  { name: "Medium Spring Green", color: "#00FA9A" },
  { name: "Chocolate", color: "#D2691E" },
  { name: "Dark Turquoise", color: "#00CED1" },
  { name: "Tomato", color: "#FF6347" },
  { name: "Slate Blue", color: "#6A5ACD" },
  { name: "Pale Violet Red", color: "#DB7093" },
  { name: "Light Sea Green", color: "#20B2AA" },
  { name: "Light Salmon", color: "#FFA07A" },
  { name: "Medium Violet Red", color: "#C71585" },
  { name: "Turquoise", color: "#40E0D0" },
  { name: "Maroon", color: "#800000" },
  { name: "Powder Blue", color: "#B0E0E6" },
  { name: "Medium Slate Blue", color: "#7B68EE" },
  { name: "Dark Orange", color: "#FF8C00" },
  { name: "Slate Gray", color: "#708090" },
  { name: "Brown", color: "#A52A2A" },
  { name: "Medium Purple", color: "#9370DB" },
  { name: "Saddle Brown", color: "#8B4513" },
  { name: "Peach Puff", color: "#FFDAB9" },
  { name: "Forest Green", color: "#228B22" },
  { name: "Plum", color: "#DDA0DD" },
  { name: "Dodger Blue", color: "#1E90FF" },
  { name: "Yellow Green", color: "#9ACD32" },
  { name: "Cornflower Blue", color: "#6495ED" },
  { name: "Deep Pink", color: "#FF1493" },
  { name: "Medium Aquamarine", color: "#66CDAA" },
  { name: "Light Pink", color: "#FFB6C1" },
];

// ?backend ..............................................................................
export const JWT_SECRET = "hgvbhjbkjbvhjbhvngcghch";
